version: '3.8'

services:
  go-api-server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: go-api-server
    environment:
      - API_KEY=${API_KEY:-mysecretkey}
      - MAX_REQUESTS_PER_MINUTE=${MAX_REQUESTS_PER_MINUTE:-10}
    volumes:
      - ../cert.pem:/app/cert.pem
      - ../key.pem:/app/key.pem
    expose:
      - "8080"
    networks:
      - app-network

  web-frontend:
    build:
      context: web
      dockerfile: Dockerfile
      container_name: web-frontend
      networks:
        - app-network

  nginx:
      build:
        context: docker
        dockerfile: Dockerfile.nginx
      container_name: nginx-reverse-proxy
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./cert.pem:/etc/nginx/ssl/cert.pem
        - ./key.pem:/etc/nginx/ssl/key.pem
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - go-api-server
        - web-frontend
      networks:
        - app-network
networks:
  app-network:
    driver: bridge
