# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Create the SSL directory
RUN mkdir -p /etc/nginx/ssl

# Copy the ssl files to the container
COPY ../cert.pem /etc/nginx/ssl/cert.pem
COPY ../key.pem /etc/nginx/ssl/key.pem

# Expose ports 80 and 443
EXPOSE 80 443

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
